create table users
(
    user_id    bigint generated by default as identity
        primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    role       smallint
        constraint users_role_check
            check ((role >= 0) AND (role <= 2))
);

create table parent
(
    user_id bigint not null
        primary key
        constraint user_id_fkey
            references users
);

create table student
(
    user_id        bigint not null
        primary key
        constraint user_id_fkey
            references users,
    parent_user_id bigint
        constraint parent_user_id_fkey
            references parent
);

create table teacher
(
    subject varchar(255),
    user_id bigint not null
        primary key
        constraint user_id_fkey
            references users
);
